### PR TITLE
PA Dept of Environmental Protection

### PR DESCRIPTION
**Pull request by henryCraig**
Feeling a little lost after not checking in for some time on this project.  Currently the code appears to return the title, start_time, description, and location well.  It's also my understanding that the code is currently passing the style constrants, although the finished product will have a lot more comments removed.  I do have a few questions though:
1 - There aren't end times on all, or even most of, the events - should I consider those all-day?  Even if there's nothing else to indicate an all day status?
2 - I haven't seen anything strictly indicating an all day status - so should that always return False?
3 - Regex doesn't seem to be finding "am" or "pm", I can work around that for start and end times, but if anyone has the solution I would appreciate some advice on it.
4 - In terms of links occasionally there's a web address but there's always an email.  Do we want both scraped?

Any other advice would be appreciated!  Thanks for the help!

### CODE REVIEW

**Comment by ben-nathanson** [comment]
1. You can leave the end time as `None` if there is no end time.
1. Returning false sounds good to me!
1. I don't have a specific regex for this one, but I have been seeing folks split the string using spaces and then parse it from there. Looking at the page, you have things like `12/17/2019 9:00 am : Environmental Quality Board (EQB) meeting`. If we were to call re.split using a space, you could just parse the resulting array for "am" or "pm". So as you're traversing the array, you get `9:00` immediately followed by `am`. Still a bit hack-ish but I think that would do the trick. 
1. As far as I know we don't want e-mails, but in the long term I like the idea of there being a contact field. 

I'm excited to see your progress! Let me know if that answered your questions. I'll be at C&S tonight.

**Comment by ben-nathanson** [comment]
Just ran your code - output looks good so far! Let me know when you're ready to move it out of WIP.

**Comment by henryCraig** [comment]
Currently I don't have the time notes returning anything, but otherwise I think it's basically done(?)!  In terms of returning the location it's not formatted the same way every time, so for now I'm returning an untitled "name" with all the information one would need in the "address" portion.  I don't fully understand what it means for the Travis CI checks to be failing either, but I'll be at the meeting this weekend to hopefully discuss the issue further.

**Comment by henryCraig** [comment]
Hoping to close https://github.com/bonfirefan/city-scrapers-pitt/issues/44

**Comment by bonfirefan** [comment]
A reminder to sync this with the upstream fork so that Travis tests will past! Also, to enable edits from maintainers!

**Enable edits from maintainers!**:
> I[n the the right sidebar of your pull request, select Allow edits from maintainers. You can change these permissions at any time by unselecting this option.](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)

**Syncing your fork**:
```
git remote add upstream https://github.com/bonfirefan/city-scrapers-pitt.git
git fetch upstream
git merge upstream/master
```

**Comment by henryCraig** [comment]
Allow edits from maintainers is currently checked.  Upstream was already created, but I just did the fetch and merge.  Thanks for looking!

**Comment by ben-nathanson** [comment]
Closed by #80

**Pull request closed without merging**
