### PR TITLE
[WIP] Spider pa liquorboard

### PR DESCRIPTION
**Pull request by lyons7**

### CODE REVIEW

**Comment by bonfirefan** [comment]
Hey @lyons7, great work! We made an update because our testing environment got unhappy - if you can merge in changes from `upstream/master` that would be great.

**Comment by bonfirefan** [comment]
This pull ruquest addresses Issue #24

**Comment by lyons7** [comment]
Hi Bonnie! I would very happily do this, but I am not sure how! Is this
something I do in Github or via the command line? Sorry! i've been googling
this all week and can't figure it out what exactly I need to do. Thanks for
your help, I appreciate it!

Kate

**Comment by ben-nathanson** [comment]
To close an issue via the command line, add the phrase `Closes: #[issue number]` to the commit message. For example if I had an issue number 1 that I wanted to close, I would do `git commit -m "Closes: #1"`. Let me know if that helps!

**Pull request merged**
