### PR TITLE
Spider pitt city planning

### PR DESCRIPTION
**Pull request by dkori**
Created a working spider for Pittsburgh City Planning hearings and notices: http://pittsburghpa.gov/dcp/notices.

### CODE REVIEW

**Comment by dkori** [comment]
Fixed formatting issues that were causing YAPF to fail in latest push

**Comment by pjsier** [comment]
@bonfirefan want me to take a look at this? Not sure if that was intentional

**Comment by dkori** [comment]
Sorry, I requested a review in error

**Comment by bonfirefan** [comment]
This is a ping to all! See if you can enable edits from maintainers!

**Enable edits from maintainers!**:
> I[n the the right sidebar of your pull request, select Allow edits from maintainers. You can change these permissions at any time by unselecting this option.](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)

**Pull request merged**
