### PR TITLE
Pgh city council spider

### PR DESCRIPTION
**Pull request by jtotoole**
Closes https://github.com/bonfirefan/city-scrapers-pitt/issues/3, which looks like it hasn't been touched for a while. I had occasion to poke around on Legistar for unrelated reasons, so figured I'd take a stab at this 🙂

### CODE REVIEW

**Comment by bonfirefan** [comment]
Thanks for putting this together, James! It looks good to me but I'll be doing another check later on. Thanks for flagging the timezone issue with `city-scrapers-core`.

**Comment by jtotoole** [comment]
Thank you! in addition to the tz issue with `datetime` objects in `city-scrapers-core`, it looks to me like there's a problem with the `genspider` command: It automatically sets the timezone to `America/Chicago`, and doesn't accept arguments to adjust that. That will likely be a gotcha for people doing Pittsburgh spiders. I can probably take a stab at that fix in the future unless someone wants to pick it up now.

**Comment by danwarren** [comment]
I was also distracted by the core tz issue, it's reasonably trivial to edit the template on a local virtualenv, but not very shareable. I only spent about 30 min in the core repo, but did not find a config override that could solve it without some non-trivial coding.

**Comment by jtotoole** [comment]
Made a PR for the `_get_status` issue here fyi: https://github.com/City-Bureau/city-scrapers-core/pull/6

**Comment by jtotoole** [comment]
Based on the convo in the PR I linked to above, sounds like there's actually no need to make the `datetime` timezone-aware; adjusted this PR accordingly

**Pull request merged**
